### ISSUE TITLE
NPM error

### ISSUE THREAD

**Issue by chrisheuberger** [IDEOorg/steps-guide-housing#1]
When I follow the instructions in the README and run `npm run start` I get the following error:

```
[BS] Serving files from: src
[BS] Watching files...
webpack: wait until bundle finished: /index.html
2018-07-11 15:23 node[45273] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-07-11 15:23 node[45273] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
npm ERR! code ELIFECYCLE
...
```

`http://localhost:3000/` opens up but says site cannot be reached. I'm running node version 6.10.2 and npm version 6.0.0. Any ideas?

**Comment by chrisheuberger** [comment]
Not sure why this did it but referencing [this issue](https://github.com/sunfmin/notebook/issues/31), I ran

```
brew install watchman
```

and that solved the issue.
